# yo_berry_dark - darker yo berry variant

# Helix theme inspired by Zenbones & Alabaster.
# Author: Michael McClintock @mrmcc3
# License: MIT

inherits = "yo_berry"

[palette] # radix ui colors

# primary - mauveDark. shift p1-p5 -> p2-p6

p2 = "#121113"
p3 = "#1a191b"
p4 = "#232225"
p5 = "#2b292d"
p6 = "#323035"

