# yo_dark - darker yo variant

# Helix theme inspired by Zenbones & Alabaster.
# Author: Michael McClintock @mrmcc3
# License: MIT

inherits = "yo"

[palette]

# in the default theme p1 is unused. shift p1-p5 -> p2-p6

p2 = "#161615"
p3 = "#1c1c1a"
p4 = "#232320"
p5 = "#282826"
p6 = "#2e2e2b"
