# yo_light

# Helix theme inspired by Zenbones & Alabaster.
# Author: Michael McClintock @mrmcc3
# License: MIT

inherits = "yo"

[palette] # radix ui colors

# primary - sand
p1 = "#fdfdfc"
p2 = "#f9f9f8"
p3 = "#f3f3f2"
p4 = "#eeeeec"
p5 = "#e9e9e6"
p6 = "#e3e3e0"
p7 = "#dbdbd7"
p8 = "#c8c7c1"
p9 = "#90908c"
p10 = "#868682"
p11 = "#706f6c"
p12 = "#1b1b18"

error = "#dc3d43" # red-10
warning = "#ed5f00" # orange-10
info = "#0081f1" # blue-10
