# yo_light

# Helix theme inspired by Zenbones & Alabaster.
# Author: Michael McClintock @mrmcc3
# License: MIT

inherits = "yo"

[palette] # radix ui colors

# primary - sand
p1 = "#fdfdfc"
p2 = "#f9f9f8"
p3 = "#f1f0ef"
p4 = "#e9e8e6"
p5 = "#e2e1de"
p6 = "#dad9d6"
p7 = "#cfceca"
p8 = "#bcbbb5"
p9 = "#8d8d86"
p10 = "#82827c"
p11 = "#63635e"
p12 = "#21201c"

error = "#dd4425" # tomato-10
warning = "#ffba18" # amber-10
info = "#0588f0" # blue-10

string = "#46a758" # grass-9
constant = "#8e4ec6" # purple-9
keyword = "#a18072" # bronze-9

