# Helix theme inspired by Zenbones & Alabaster with radix colors.
# Author: Michael McClintock @mrmcc3
# License: MIT

inherits = "yo_sand"

[palette]

# sand
p1 = "#fdfdfc"
p2 = "#f9f9f8"
p3 = "#f1f0ef"
p4 = "#e9e8e6"
p5 = "#e2e1de"
p6 = "#dad9d6"
p7 = "#cfceca"
p8 = "#bcbbb5"
p9 = "#8d8d86"
p10 = "#82827c"
p11 = "#63635e"
p12 = "#21201c"

error = "#dd4425" # tomato-10
warning = "#ffba18" # amber-10
info = "#0797b9" # cyan-10

string = "#3e9b4f" # grass-10
constant = "#cf3897" # pink-10
keyword =  "#815e46" # brown-11

